# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

submodules:
  include: all
  recursive: true

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - cmake
  jobs:
    pre_build:
      - cmake -S . -B INSTALL/BUILD -DCMAKE_INSTALL_PREFIX=INSTALL -DPOLYCLIPPER_ENABLE_DOCS=1 -DPOLYCLIPPER_MODULE_GEN=0 -DPOLYCLIPPER_ENABLE_TESTS=0
      - ls INSTALL/BUILD/
      - ls INSTALL/BUILD/_build
      - cat INSTALL/BUILD/_build/conf.py

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: INSTALL/BUILD/_build/conf.py
